# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Techtic_practical' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Techtic_practical
	
  pod 'Alamofire', '~> 5.2'
  pod 'SDWebImage', '~> 5.0'
  pod 'ReachabilitySwift', '~> 4.2.0'


end
